---
name: Check PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  enforce-labels:
    name: Enforce labels
    runs-on: ubuntu-latest
    steps:
      - name: Enforce labels
        uses: bitwarden/gh-actions/enforce-labels@main
