---
name: Workflow linter

on:
  pull_request:
    paths:
      - .github/workflows/**

permissions: read-all

jobs:
  call-workflow:
    name: Lint
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@main
    permissions:
      contents: read
      checks: write
      pull-requests: write
